#set document(title: "$if(title)$$title$$else$DeepBrief$endif$")
#let ink = rgb("#171717")
#let muted = rgb("#5b6460")
#let rule = rgb("#d8e0dd")
#let panel = rgb("#f6f8f6")
#let zebra = rgb("#f7faf8")
#let code-bg = rgb("#eef3f0")
#let accent = rgb("#1f6f63")
#let accent-dark = rgb("#17483f")

#set page(
  paper: "us-letter",
  margin: (x: 0.74in, y: 0.76in),
  footer: context {
    set text(size: 8pt, fill: muted)
    let before = query(selector(heading.where(level: 1)).before(here()))
    let name = if before.len() > 0 { before.last().body } else { [DeepBrief] }
    grid(
      columns: (1fr, auto),
      align: (left, right),
      name,
      counter(page).display("1"),
    )
  },
)
#set text(size: 10pt, fill: ink)
#set par(justify: false, leading: 0.66em, spacing: 0.76em)
#set heading(numbering: "1.1")
#set table(
  inset: 4pt,
  align: left,
  stroke: (x, y) => if y == 0 { (bottom: 1pt + accent) } else { (bottom: 0.5pt + rule) },
  fill: (x, y) => if y == 0 { panel } else if calc.odd(y) { zebra } else { white },
)

#show heading.where(level: 1): set text(size: 16pt, fill: accent-dark, weight: "bold")
#show heading.where(level: 1): set block(above: 1.6em, below: 0.8em)
#show heading.where(level: 2): set text(size: 12.4pt, fill: accent-dark, weight: "bold")
#show heading.where(level: 3): set text(size: 10.8pt, fill: accent, weight: "bold")
#show heading: set block(sticky: true)

#show link: it => text(fill: accent-dark)[#underline(it)]

#show table.cell.where(y: 0): set text(weight: "bold", fill: accent-dark, size: 9pt)
#show table.cell: set text(size: 9pt)

#show figure.caption: it => block(width: 90%)[
  #text(size: 8.5pt, fill: muted, style: "italic")[#it]
]

// Float image figures to the top/bottom of the page so a figure that does not
// fit the remaining space lets text backfill instead of leaving the page half blank.
#show figure.where(kind: image): set figure(placement: auto)

#show raw.where(block: false): it => box(
  fill: code-bg,
  inset: (x: 2.2pt, y: 0.8pt),
  radius: 2pt,
)[#text(font: "New Computer Modern Mono", size: 8.7pt, fill: accent-dark)[#it]]

#show raw.where(block: true): it => block(
  fill: code-bg,
  stroke: rule,
  inset: 8pt,
  radius: 3pt,
  width: 100%,
)[#text(font: "New Computer Modern Mono", size: 7.4pt, fill: rgb("#1e2b27"))[#it]]

#show quote: it => block(
  fill: panel,
  stroke: (left: 2.5pt + accent, top: 0.5pt + rule, right: 0.5pt + rule, bottom: 0.5pt + rule),
  inset: 9pt,
  radius: 3pt,
  width: 100%,
)[#it]

// Cover page
#v(1.2in)
#text(size: 27pt, weight: "bold", fill: accent-dark)[$if(title)$$title$$else$DeepBrief$endif$]
$if(subtitle)$
#v(0.5em)
#text(size: 13pt, fill: accent)[$subtitle$]
$endif$
$if(date)$
#v(0.7em)
#text(size: 11pt, fill: muted)[$date$]
$endif$
#v(0.9em)
#line(length: 100%, stroke: 1.5pt + accent)
$if(abstract)$
#v(1.2em)
#block(
  fill: panel,
  stroke: (left: 3pt + accent),
  inset: 12pt,
  radius: 3pt,
  width: 100%,
)[$abstract$]
$endif$
#v(1fr)
#text(size: 8.5pt, fill: muted)[Generated by DeepBrief - Codex-native run]
#pagebreak()

#outline(title: "Contents", depth: 2)
#pagebreak()

$body$
